### ISSUE TITLE
cmd+shift+click opens in new window

### ISSUE THREAD

**Issue by deepfriedmind** [danielnixon/link-fixer#17]
**Describe the bug**
When clicking a link while holding down cmd+shift, the link opens in a new window. This also applies to links that aren't _broken_ without the extension.

**Expected behavior**
The link should open in a new tab in the foreground, as is default behavior.

**Browser**
 - OS: macOS 10.14.5
 - Browser: Chrome
 - Version: 75.0.3770.100

**Comment by danielnixon** [comment]
Thanks @deepfriedmind. Published as version 1.11.
