### ISSUE TITLE
Extension does not respect Firefox's "Open in foreground tab" setting

### ISSUE THREAD

**Issue by oleksandr-yefremov** [danielnixon/link-fixer#2]
Hi, thanks for writing this extension!
Now here is the bug:
1. Install link-fixer
2. Go to Firefox settings (`about:preferences`) -> Tabs section -> Check "Open tabs in foreground" (or smth similar, I have it in different language)

Expected result:
Cmd+click should open a tab in a foreground (switch to it)

Actual result:
Cmd+click always opens a tab in background (next to current tab)

Unfortunately, without this setting the extension is useless for me.

**Comment by danielnixon** [comment]
@oleksandr-yefremov I've just released version 1.10 which exposes an open in foreground/background option.
