### ISSUE TITLE
Donate link

### ISSUE THREAD

**Issue by Aquind** [danielnixon/link-fixer#497]
**Is your feature request related to a problem? Please describe.**
The problem is that I would like to donate in thanks to your efforts but there is no link that I can see to do so.

**Describe the solution you'd like**
Add a donate link to the plugin description. or 'about' page (or whatever it is called)

**Describe alternatives you've considered**
I have seen paypal, venmo links among the most common.  

**Additional context**
none that I can think of although I am not sure why more downloads of this haven't happened.  Thanks again!

**Comment by danielnixon** [comment]
That is very kind of you @Aquind, thank you. I'm not accepting donations. If you would like, please consider donating to Mozilla, UNICEF, the Fred Hollows Foundation or another charity of your choice.

**Comment by Aquind** [comment]
Will do.  Thanks :)
