### ISSUE TITLE
Not working on https://userstyles.org f.e.

### ISSUE THREAD

**Issue by eMPee584** [danielnixon/link-fixer#6]
CTRL+click on https://userstyles.org (which was the reason i found this) does not work.. Shift+Click link fixing does work though..

**Comment by danielnixon** [comment]
If I disable link-fixer I can reproduce the issue (the sidebar links - home, editor's choice, most popular...) but after re-enabling link-fixer ctrl+click works. Can you tell me more about your setup?

**Comment by StanGets** [comment]
Link Fixer 1.7 / Firefox 65.0.2 (x64) / Windows 7 (x64)

I tested the  https://userstyles.org page and Ctrl+Click link (those on the left) worked correctly though the tab opened in the background even though I do have` ("browser.tabs.loadInBackground", false);`

**Comment by danielnixon** [comment]
@StanGets load in background is a known issue: https://github.com/danielnixon/link-fixer/issues/2
