### ISSUE TITLE
Middle-Click support

### ISSUE THREAD

**Issue by eMPee584** [danielnixon/link-fixer#7]
Websites also mess with middle-click opening.. yes they do! :angry:

**Comment by rygo11** [comment]
+1 middle-click is driving me crazy on some sites. Would be awesome to extend this addon to support middle-click.

**Comment by danielnixon** [comment]
Could you provide some examples?

**Comment by rygo11** [comment]
Thanks for getting back to me. This is the culprit I found today:
https://www.gumtree.com.au/s-cars-vans-utes/sunshine-coast/toyota/k0c18320l30062

scroll down below the sponsored links to the listings,  and middle click one, eg:
![image](https://user-images.githubusercontent.com/27833995/53694662-d751e700-3dfd-11e9-95b2-f2a6be35a85d.png)

For me this opens in the same tab, not a new tab. If I ctrl-click then it opens in a new tab.

**Comment by danielnixon** [comment]
Released as version 1.7 for Firefox and Chrome. Thanks @eMPee584 & @rygo11

**Comment by rygo11** [comment]
This is excellent, thanks @danielnixon , working perfectly.
