### ISSUE TITLE
Not working at 56

### ISSUE THREAD

**Issue by zakius** [danielnixon/link-fixer#8]
Essential features should work with no issues at 56 but currently it breaks middle and modified clicks completely due to inability to load settings.

If you don't mind I'll come up with a workaround with default value or even some config panel because 56 doesn't support browserSettings at all.

EDIT: it seems that browserSettings property does exist but newTabPosition isn't there. Checking for it's existence makes it work falling back to defaults.

**Comment by danielnixon** [comment]
Released as version 1.8. Thanks @zakius

**Comment by zakius** [comment]
@danielnixon it seems that you uploaded wrong package to AMO (not sure about Chrome) as it doesn't contain this fix

**Comment by danielnixon** [comment]
@zakius Yikes. Sorry about that. I've uploaded version 1.9 to AMO containing this fix.
